CREATE TABLE [dbo].[PERSONA]
(
[CODPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APEPATPER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APEMATPER] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNIPER] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEFPER] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOMPER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LUGDOMPER] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PERSONA_pk] PRIMARY KEY CLUSTERED  ([CODPER]) ON [PRIMARY]
GO
